### ISSUE TITLE
de-duplication - logic update

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectApi#7]
Just as we discussed, currently when the voucher type is "Paper", a new voucher is always created.

But I would like to add a new test before creating the voucher: 

**Verify that the client does not already have a paper-voucher with the same voucher #.**

If the client already have a voucher with the same #, do nothing.
If it is not the case, proceed to the voucher creation.

**Comment by jturtler** [comment]
Hi, Bruno.

A bit of things to check/confirm:

- All these are about when there is the matching duplicate client, right?
- We tell the matching client by looking at CUIC first and do the exact value match of the 'trackedEntityAttributes' of 'duplicateUserCheck' (setup on config).
- In "If it is not the case, proceed to the voucher creation", since we only checked the voucher # within same client, there is a chance that other client could have same voucher #, thus resulting in xxxxxxxx-1.  
But, if that is the case, if same client sends the same voucher again, it will not match since xxxxxxxx and xxxxxxxx-1 would be considered as different voucher number?
For this reason, we could consider xxxxxxxx-1(and up) as same voucher # as xxxxxxxx?
